### ISSUE TITLE
[Feature] Default difficulty modify

### ISSUE THREAD

**Issue by mavproductions** [lengran/OpenPrefirePrac#10]
Hey Lengran!

Just wondering if you could add a default difficulty option. The current mode I personally find way too easy, and find myself leaning towards using `Harder`. Any chance you can add an option to give server-ops a difficulty default modifier?

Appreciate your work!

Thanks,

**Comment by lengran** [comment]
Sure. I'll make that.

**Comment by lengran** [comment]
Hi Mav!

I just implemented the feature you requested. It will be included in next release. But if you want to test it now, you can download it from [here](https://github.com/lengran/OpenPrefirePrac/actions/runs/8758500185). An explanation of how it works is provided [here](https://github.com/lengran/OpenPrefirePrac?tab=readme-ov-file#adjust-default-settings).

Thank you for your feedback. Have a nice day!

**Comment by mavproductions** [comment]
Noice! I'll fling it to my server then! Thanks a milli! 

Have a great weekend!
