### ISSUE TITLE
可以把菜单做成CenterHtml类型的吗

### ISSUE THREAD

**Issue by Soramagic7** [lengran/OpenPrefirePrac#19]
我感觉菜单显示在中间提示框会更直观一点

**Comment by lengran** [comment]
如果需要的话，我可以试试搞一个可选项出来，自己选用哪种菜单。不过感觉这个区别不是很大，最后都是用聊天框交互……最理想的还是能有 CSGO 时代的那种可以直接按键交互的漂浮的菜单，个人比较期待那个出来。

**Comment by Soramagic7** [comment]
您可以看看这个 https://github.com/Interesting-exe/WASDMenuAPI
我看起来好像是可以使用方向键操控菜单的源代码，这样就可以变得方便一些，我也不是很懂0.0

**Comment by lengran** [comment]
CSS 有个类似的 [PR](https://github.com/roflmuffin/CounterStrikeSharp/pull/422)，可能等他成为标准的菜单之后会考虑，不然服务器管理员配置起来还是有些麻烦。而且这个效果其实也不如 CSGO 的菜单方便……

**Comment by lengran** [comment]
那先不急着做这个了，再等等 CSS 菜单系统的更新吧，不然单纯一个 CenterHTML 感觉使用体验不会有太大的优化。我还是想等可以直接交互的菜单系统出来再重做。
