### ISSUE TITLE
可以出个自由选择武器的功能

### ISSUE THREAD

**Issue by Soramagic7** [lengran/OpenPrefirePrac#20]
这样打CT的前顶，回防之类的路线用M4的话，感觉会比较符合情境，老是从购买菜单买有点小麻烦，而且死多了后面还会没钱)

**Comment by lengran** [comment]
选择武器的话好像有其他的插件专门做这个的，我再做感觉有点重复，如果和那些插件有兼容性问题，我可以做一个配置文件里的开关，决定要不要给玩家分配武器。至于没钱的问题好解决，下个版本就加上每次复活重置满 60000 块钱。

**Comment by Soramagic7** [comment]
我有用这个 https://github.com/onurcanertekin/cs2-simple-guns-menu 搭配您的预瞄插件一起用，感觉效果还可以，只是有选了主武器情况下手枪会消失的bug，总体问题不大；
我只是希望您的插件可以更完美一点0.0，这样我就可以少装点其他插件了，服务器性能也会好些。

**Comment by lengran** [comment]
我还是想尽量让功能划分更简单清晰一点，不做全家桶，不重复实现别的插件实现过的功能。既然和这个插件的兼容上有 bug，下个版本就加上给玩家分配武器的开关吧，看看如果我的插件不修改玩家装备还有没有手枪丢失的 bug。

**Comment by Soramagic7** [comment]
期待一下！
