### ISSUE TITLE
Bot running

### ISSUE THREAD

**Issue by KsOdo666** [lengran/OpenPrefirePrac#21]
hey, is there a fix to bots constantly running in place while running a practice?

**Comment by lengran** [comment]
Is it all bots on the loose or it's just one? Could you please provide your CSS version, metamod version, and steps to reproduce this problem?

**Comment by KsOdo666** [comment]
it happens only on the hard aimlock mode i think, since like 3 months, most of the bots keep running in place like every single run for me. Just switched to the easy mode to eliminate this issue but now bots look at random places and are weird to hit.
Maybe add a passive bot feature? The issue has been happening for like a few versions of css and metamod so its not the dependency

**Comment by lengran** [comment]
By the hard aimlock mode do you mean setting "BotAimLock" to 2 in default_cfg.json? Does this problem happen constantly in every time you practice or it happens occasionally? Would you mind share the startup command used to start the server?

I haven't encountered this problem myself before but I'll test it on the latest version of game and CSS again, and see if I can reproduce the problem. If any progress is made, I'll let you know. Thanks for giving this feedback. :)

**Comment by KsOdo666** [comment]
yeah botaimlock 2, i use default mattchzy prematch for practicing, it happens every time i practice on the aimlock mode mentioned
bot_kick
bot_quota 0
mp_autokick 0
mp_autoteambalance 0
mp_buy_anywhere 0
mp_buytime 15
mp_death_drop_gun 0
mp_free_armor 0
mp_ignore_round_win_conditions 0
mp_limitteams 0
mp_respawn_on_death_ct 0
mp_respawn_on_death_t 0
mp_solid_teammates 0
mp_spectators_max 20
mp_maxmoney 16000
mp_startmoney 16000
mp_timelimit 0
sv_alltalk 0
sv_auto_full_alltalk_during_warmup_half_end 0
sv_deadtalk 1
sv_full_alltalk 0
sv_hibernate_when_empty 0
mp_weapons_allow_typecount -1
sv_infinite_ammo 0
sv_showimpacts 0
sv_voiceenable 1
tv_relayvoice 1
sv_cheats 0
mp_ct_default_melee weapon_knife
mp_ct_default_secondary weapon_hkp2000
mp_ct_default_primary ""
mp_t_default_melee weapon_knife
mp_t_default_secondary weapon_glock
mp_t_default_primary
mp_maxrounds 24
mp_warmup_start
mp_warmup_pausetimer 1
mp_warmuptime 9999
cash_team_bonus_shorthanded 0

**Comment by lengran** [comment]
Sorry for the late reply. I've been quite busy these days. There was a time when I tried to reproduce the problem but failed. Hopefully I'll have more time to diagnose this problem next week. I'll post any update here in this thread.

**Comment by lengran** [comment]
Hi! I tried many times to reproduce the problem but in every run the issue didn't happen even once. Could it be because of other plugins? You might want to use a multi-mod setup plugin to create separate environment for each plugin to avoid interference. 

Can you see any error or exception in console logs? It would be helpful if any additional information is provided to debug this issue.
