### ISSUE TITLE
Bots are disappearing after the !prefire prac 1 or any number

### ISSUE THREAD

**Issue by YD-S** [lengran/OpenPrefirePrac#22]
Maybe its server config but they dont disappear if i play practice mode on matchzy. They sapwn but disappear later.

**Comment by YD-S** [comment]
console says

**Comment by YD-S** [comment]
Could not add bot to the game: Team is full
Could not add bot to the game: Team is full
[OpenPrefirePrac] Map de_mirage doesn't have breakables to break.
Could not add bot to the game: Team is full
Could not add bot to the game: Team is full
Could not add bot to the game: Team is full
'Muhlik' took 6.6ms to execute 1 commands, backlog is 0 commands
37.781250 Long frame (WarmupPeriod): 36.96ms elapsed, 6.95ms sim time, 1 ticks, 2418..2418.
'👑 𝓡𝓸𝔂𝓪𝓵𝓮': CQ resync (slow_frame), client will discard cmd timing < 803
37.890625 Long frame (WarmupPeriod): 23.57ms elapsed, 23.39ms sim time, 1 ticks, 2425..2425.
'👑 𝓡𝓸𝔂𝓪𝓵𝓮': CQ resync (slow_frame), client will discard cmd timing < 809
Stone kicked by Console (NETWORK_DISCONNECT_KICKED)
Soldier kicked by Console (NETWORK_DISCONNECT_KICKED)
ClientPutInServer create new player controller [Rip]
[OpenPrefirePrac] Bot Rip, slot: 8 has been spawned.
"Rip<8><BOT><Unassigned>" ChangeTeam() CTMDBG , team 0, req team 3 willSwitch 0, 38.28
[MatchZy] Kicking bot Rip due to erroneous spawning
38.281250 Long frame (WarmupPeriod): 26.71ms elapsed, 23.44ms sim time, 1 ticks, 2450..2450.
'👑 𝓡𝓸𝔂𝓪𝓵𝓮': CQ resync (slow_frame), client will discard cmd timing < 834
Operator kicked by Console (NETWORK_DISCONNECT_KICKED)
Muhlik kicked by Console (NETWORK_DISCONNECT_KICKED)
Buckshot kicked by Console (NETWORK_DISCONNECT_KICKED)
Rip kicked by Console (NETWORK_DISCONNECT_KICKED)
RemoveArrayElementsOutsideOfArrayMetadataBounds:  CCSGOViewModel [ent 256] removing change '3/4/50' for field  (value '') on array that has metadata with only 50 array elements!

**Comment by YD-S** [comment]
and it says warmup

**Comment by lengran** [comment]
Warmup is correct. It seems you have exceeded the player number limit on your server. Did you set anything related to team sizes? What is your maxplayer setting?

**Comment by YD-S** [comment]
I have matchzy too, and in console it says [mathczy] erroneous spawning kicking bot xxx

Is there any way to play prefire with matchzy active too?

**Comment by lengran** [comment]
Ah. That's the problem. If you are running Matchzy and OPP simultaneously, you might run into such problems. Both Matchzy and OPP try to manage bots, which interfere with each other. I would suggest using a multi-addon setup which activates a set of compatible plugins at a time and disable others automatically. There are tools like [cs2-modded-server](https://github.com/kus/cs2-modded-server) that can do this for you.

**Comment by YD-S** [comment]
okay TY
