### ISSUE TITLE
Can u make bots spawn instantly?

### ISSUE THREAD

**Issue by DaVinc11** [lengran/OpenPrefirePrac#23]
I have a question same as in title, can u make bots spawn instanlty after u respawn? Now u have to wait 1-2 seconds after u die for bots to respawn. Love ur plugin my friend btw

**Comment by lengran** [comment]
Thanks for you love of this project. <3

That time is for server to response. On low spec servers or server with heavy plugin loads, timing might be critical. One possible choice is that you could fork this project and change the timer values. This project has auto build actions, so there is no need of building a separate building environment. All changes you pushed to your forked repo will be automatically compiled. So you can find the perfect values for your server.

**Comment by DaVinc11** [comment]
Well im hosting it on my private pc (ryzen 7 7800x3d, rtx 3080ti and 32gb of ram with samsung nvme drive) which i dont think is a bad setup. I have some other plugins like skin changer and and very basic pracc plugin, so i dont think it is the problem. Well im newbie when it comes to making/editing plugins i never did that so im not sure what are u talking about hahaha. But anyway it is not that big of a problem and than u for ur reply :)

**Comment by lengran** [comment]
:heart:
