### ISSUE TITLE
有什么指令开始预瞄训练吗？

### ISSUE THREAD

**Issue by WangChuDi** [lengran/OpenPrefirePrac#5]
服务器启动之后就还是和没加插件一样，是有什么指令才进入预瞄模式吗？另外readme里提到的多人同时进行育苗训练要怎么实现呢？另外服务器的日志已附在附件中
[server.log](https://github.com/lengran/OpenPrefirePrac/files/14717374/server.log)

**Comment by lengran** [comment]
不好意思，之前上传的压缩包里缺少了一个文件，现在已经修复了，非常感谢您反馈的信息！可以下载新的压缩包重新安装。进入预瞄模式可以直接聊天框输入 “!prefire”。多人练习的话，假如两人选择的练习路线没有冲突，应该是开箱即用的，不过因为我一个人很难测试两人练习的情况，可能存在 bug，如果有问题还请再反馈。

**Comment by WangChuDi** [comment]
十分感谢！刚刚测试已经可以使用了！晚上拉朋友试试多人练习的功能。
