### ISSUE TITLE
[BUG]部分路线击杀前几个bot不会加血

### ISSUE THREAD

**Issue by WangChuDi** [lengran/OpenPrefirePrac#7]
如题在inferno中测试，前几个bot有概率不加血，同时也不会跳出剩余几个bots的提示。看了看代码可能是
`if (targetNo >= _practices[practiceIndex].NumBots)`这个判断相关代码出错了？

**Comment by lengran** [comment]
可以提供下复现方法吗？

**Comment by lengran** [comment]
因为具体不太清楚这种情况是怎么产生的，目前我发现了一个可能导致问题的 bug，尝试做了修复，可以试试 [这个修复后的版本](https://github.com/lengran/OpenPrefirePrac/actions/runs/8416927024/artifacts/1354865400) 是否解决了问题。

如果方便的话，还是想请您描述下问题出现的条件，比如有几人在进行练习，是练习了一段时间后出现问题还是刚开始练习就出现了等等。如果能有复现的步骤会更好。

最后，非常感谢您的反馈信息！

**Comment by WangChuDi** [comment]
现在发现是服务器启动项使用maxplayer_override 64 就不会出现，不使用或者maxplayer 64这样就会出现bug。另外是单人训练，刚开服训练的时候就会出现。

**Comment by WangChuDi** [comment]
如果需要日志的话：
[240325server.log](https://github.com/lengran/OpenPrefirePrac/files/14743141/240325server.log)

**Comment by WangChuDi** [comment]
> 因为具体不太清楚这种情况是怎么产生的，目前我发现了一个可能导致问题的 bug，尝试做了修复，可以试试 [这个修复后的版本](https://github.com/lengran/OpenPrefirePrac/actions/runs/8416927024/artifacts/1354865400) 是否解决了问题。
> 
> 如果方便的话，还是想请您描述下问题出现的条件，比如有几人在进行练习，是练习了一段时间后出现问题还是刚开始练习就出现了等等。如果能有复现的步骤会更好。
> 
> 最后，非常感谢您的反馈信息！

测试这个版本也会出现这个bug

**Comment by lengran** [comment]
> 现在发现是服务器启动项使用maxplayer_override 64 就不会出现，不使用或者maxplayer 64这样就会出现bug。另外是单人训练，刚开服训练的时候就会出现。

这就是原因了，不加这个的话会导致同阵营人数（bot加玩家）超限，日志里也体现了这个问题。建议使用 Readme 里推荐的启动选项。

```
-dedicated -insecure +map de_inferno -maxplayers_override 64 +game_alias competitive
```
