### ISSUE TITLE
[Feature] Adding alerts on player join on how to use prefire

### ISSUE THREAD

**Issue by mavproductions** [lengran/OpenPrefirePrac#8]
Hey @lengran !

Love all the work you've put into this mod the last little while. It runs very well on my server now. 😊

Just wondering if there's any chance you could send a simple colored chat message to users when they join the server to alert them how to use the prefire mode. Something like `Start a prefire course with the !prefire command in all chat`. 

Some of my users aren't exactly going to know how to start it unless I instruct them, so it would be nice to have this announcement. After a course is complete and while the server is waiting, maybe a prompt every so many seconds or minutes would also be good if they miss the message on their connect, but not too "floody/spammy" - if that makes sense.

Thanks again for making this. Really love this. :))))

Cheers,

**Comment by lengran** [comment]
Thank you for your valuable suggestions. Your feedback makes me understand the need of this kind of messages. After a quick thought I find that announcement messages could have general application to a variety of scenarios. So I want to make it a separate plugin for general purpose announcement broadcast. I'll start working on it tomorrow. Please let me know if you have any new thought on that.

**Comment by mavproductions** [comment]
That's the only thing that comes to mind at the moment, but I haven't tested it with multiple players yet so I need to explore some more. You might have more insight on that.

**Comment by lengran** [comment]
Hi! I've done that. Would you mind check [this](https://github.com/lengran/CS2AnnouncementBroadcaster/releases/tag/v0.0.1) out? You can put the following string in *game/csgo/addons/counterstrikesharp/plugins/CS2AnnouncementBroadcaster/cfg/messages.json*.

```json
{
    "OnPlayerConnectMsgs": [
        {
            "msg": "To enter [GREEN]prefire practice[NORMAL] mode, please type [RED]!prefire[NORMAL]."
        }
    ]
}
```

Here's the in-game screenshot. 
![4fe055b523fda890e1358e1bb3e2c6bb](https://github.com/lengran/OpenPrefirePrac/assets/20275840/828f987c-c554-4345-a6e2-a16643ded3eb)

**Comment by lengran** [comment]
I just implemented the timer triggered message. You can check it out [here](https://github.com/lengran/CS2AnnouncementBroadcaster/releases/tag/v0.2.0). If you have other suggestions please let me know.
